using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraFollow : MonoBehaviour
{
    public Transform target;
    private float sSpeed = 1000.0f;
    private Vector3 dist = new Vector3(0, 2, -15);
    private Vector3 moveLimit;

    private void Update() {
        moveLimit = new Vector3(PercentCalculator(transform.position.x, 20), PercentCalculator(transform.position.y, 20), 0);
        Vector3 dPos = target.position + dist - moveLimit;
        Vector3 sPos = Vector3.Lerp(transform.position, dPos, sSpeed * Time.deltaTime);
        transform.position = sPos;
        transform.LookAt(target.position);    
    }

    private float PercentCalculator(float val, int percent) {
        return val * percent / 100;
    }

}
